### PR TITLE
feat: add ci config, rustfmt, dependabot, etc.

### PR DESCRIPTION
**Pull request by bitwalker**

### CODE REVIEW

**Comment by bitwalker** [comment]
@bobbinth I'll merge this now, so that any subsequent PRs can pick up the CI checks and what not, but I believe this addresses all of the changes you wanted in #1. So aside from a cursory review, things should be ready to publish to crates.io whenever you are ready

**Comment by bobbinth** [comment]
I fixed some minor issues and published to [crates.io](https://crates.io/crates/miden-formatting). [Docs](https://docs.rs/crate/miden-formatting/latest) show some error, though also seem to have imported the readme correctly.

**Comment by bitwalker** [comment]
> I fixed some minor issues and published to [crates.io](https://crates.io/crates/miden-formatting). [Docs](https://docs.rs/crate/miden-formatting/latest) show some error, though also seem to have imported the readme correctly.

I'll take a look shortly and open a PR with a fix, not sure what went wrong, must be due to the changes I made though, since the docs built fine yesterday.

**Comment by bobbinth** [comment]
No rush on this at all (we can fix it later down the road). One thing: I did alter the path of the `include_str` macro - otherwise `cargo publish` didn't work (you can check it with the `--dry-run` flag).

**Pull request merged**
